name = "united-experts-api"
main = "functions/[[path]].ts"
compatibility_date = "2024-05-30"
pages_build_output_dir = "dist"

# تكوين KV للبيانات المؤقتة
[[kv_namespaces]]
binding = "CONTACT_SUBMISSIONS"
id = "contact-submissions"
preview_id = "contact-submissions"

[vars]
ENVIRONMENT = "production"
# Add your Supabase credentials here in the Cloudflare dashboard
# Do not commit them directly to this file
SUPABASE_URL = "YOUR_SUPABASE_URL"
SUPABASE_KEY = "YOUR_SUPABASE_SERVICE_KEY"

[site]
bucket = "./dist" 